/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AllStockRouteImport } from './routes/all-stock'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowToBuyRouteImport } from './routes/how-to-buy'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OnSaleRouteImport } from './routes/on-sale'
import { Route as OnePriceRouteImport } from './routes/one-price'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountSavedRouteImport } from './routes/account/saved'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminTaxonomyRouteImport } from './routes/admin/taxonomy'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CarsStockIdRouteImport } from './routes/cars.$stockId'
import { Route as AccountInquiriesIndexRouteImport } from './routes/account/inquiries/index'
import { Route as AccountInquiriesIdRouteImport } from './routes/account/inquiries/$id'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin/inquiries/index'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin/inquiries/$id'
import { Route as AdminVehiclesIndexRouteImport } from './routes/admin/vehicles/index'
import { Route as AdminVehiclesIdRouteImport } from './routes/admin/vehicles/$id'
import { Route as ApiPublicImportFeedRouteImport } from './routes/api/public/import-feed'
import { Route as ApiPublicSyncInventoryRouteImport } from './routes/api/public/sync-inventory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AllStockRoute = AllStockRouteImport.update({
  id: '/all-stock',
  path: '/all-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToBuyRoute = HowToBuyRouteImport.update({
  id: '/how-to-buy',
  path: '/how-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OnSaleRoute = OnSaleRouteImport.update({
  id: '/on-sale',
  path: '/on-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const OnePriceRoute = OnePriceRouteImport.update({
  id: '/one-price',
  path: '/one-price',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSavedRoute = AccountSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CarsStockIdRoute = CarsStockIdRouteImport.update({
  id: '/cars/$stockId',
  path: '/cars/$stockId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountInquiriesIndexRoute = AccountInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountInquiriesIdRoute = AccountInquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVehiclesIndexRoute = AdminVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVehiclesIdRoute = AdminVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicImportFeedRoute = ApiPublicImportFeedRouteImport.update({
  id: '/api/public/import-feed',
  path: '/api/public/import-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncInventoryRoute = ApiPublicSyncInventoryRouteImport.update({
  id: '/api/public/sync-inventory',
  path: '/api/public/sync-inventory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/all-stock': typeof AllStockRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/how-to-buy': typeof HowToBuyRoute
  '/inquiry': typeof InquiryRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/on-sale': typeof OnSaleRoute
  '/one-price': typeof OnePriceRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/saved': typeof AccountSavedRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/cars/$stockId': typeof CarsStockIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/inquiries/$id': typeof AccountInquiriesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/api/public/import-feed': typeof ApiPublicImportFeedRoute
  '/api/public/sync-inventory': typeof ApiPublicSyncInventoryRoute
  '/account/inquiries/': typeof AccountInquiriesIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/all-stock': typeof AllStockRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/how-to-buy': typeof HowToBuyRoute
  '/inquiry': typeof InquiryRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/on-sale': typeof OnSaleRoute
  '/one-price': typeof OnePriceRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/saved': typeof AccountSavedRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/cars/$stockId': typeof CarsStockIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/inquiries/$id': typeof AccountInquiriesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/api/public/import-feed': typeof ApiPublicImportFeedRoute
  '/api/public/sync-inventory': typeof ApiPublicSyncInventoryRoute
  '/account/inquiries': typeof AccountInquiriesIndexRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/vehicles': typeof AdminVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/all-stock': typeof AllStockRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/how-to-buy': typeof HowToBuyRoute
  '/inquiry': typeof InquiryRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/on-sale': typeof OnSaleRoute
  '/one-price': typeof OnePriceRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/saved': typeof AccountSavedRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/cars/$stockId': typeof CarsStockIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/inquiries/$id': typeof AccountInquiriesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/api/public/import-feed': typeof ApiPublicImportFeedRoute
  '/api/public/sync-inventory': typeof ApiPublicSyncInventoryRoute
  '/account/inquiries/': typeof AccountInquiriesIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/all-stock'
    | '/compare'
    | '/contact'
    | '/how-to-buy'
    | '/inquiry'
    | '/login'
    | '/new-arrivals'
    | '/on-sale'
    | '/one-price'
    | '/account/profile'
    | '/account/saved'
    | '/admin/content'
    | '/admin/profile'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/cars/$stockId'
    | '/account/'
    | '/admin/'
    | '/account/inquiries/$id'
    | '/admin/inquiries/$id'
    | '/admin/vehicles/$id'
    | '/api/public/import-feed'
    | '/api/public/sync-inventory'
    | '/account/inquiries/'
    | '/admin/inquiries/'
    | '/admin/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/all-stock'
    | '/compare'
    | '/contact'
    | '/how-to-buy'
    | '/inquiry'
    | '/login'
    | '/new-arrivals'
    | '/on-sale'
    | '/one-price'
    | '/account/profile'
    | '/account/saved'
    | '/admin/content'
    | '/admin/profile'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/cars/$stockId'
    | '/account'
    | '/admin'
    | '/account/inquiries/$id'
    | '/admin/inquiries/$id'
    | '/admin/vehicles/$id'
    | '/api/public/import-feed'
    | '/api/public/sync-inventory'
    | '/account/inquiries'
    | '/admin/inquiries'
    | '/admin/vehicles'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/about'
    | '/all-stock'
    | '/compare'
    | '/contact'
    | '/how-to-buy'
    | '/inquiry'
    | '/login'
    | '/new-arrivals'
    | '/on-sale'
    | '/one-price'
    | '/account/profile'
    | '/account/saved'
    | '/admin/content'
    | '/admin/profile'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/cars/$stockId'
    | '/account/'
    | '/admin/'
    | '/account/inquiries/$id'
    | '/admin/inquiries/$id'
    | '/admin/vehicles/$id'
    | '/api/public/import-feed'
    | '/api/public/sync-inventory'
    | '/account/inquiries/'
    | '/admin/inquiries/'
    | '/admin/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AllStockRoute: typeof AllStockRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  HowToBuyRoute: typeof HowToBuyRoute
  InquiryRoute: typeof InquiryRoute
  LoginRoute: typeof LoginRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OnSaleRoute: typeof OnSaleRoute
  OnePriceRoute: typeof OnePriceRoute
  CarsStockIdRoute: typeof CarsStockIdRoute
  ApiPublicImportFeedRoute: typeof ApiPublicImportFeedRoute
  ApiPublicSyncInventoryRoute: typeof ApiPublicSyncInventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-stock': {
      id: '/all-stock'
      path: '/all-stock'
      fullPath: '/all-stock'
      preLoaderRoute: typeof AllStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-buy': {
      id: '/how-to-buy'
      path: '/how-to-buy'
      fullPath: '/how-to-buy'
      preLoaderRoute: typeof HowToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-sale': {
      id: '/on-sale'
      path: '/on-sale'
      fullPath: '/on-sale'
      preLoaderRoute: typeof OnSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-price': {
      id: '/one-price'
      path: '/one-price'
      fullPath: '/one-price'
      preLoaderRoute: typeof OnePriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/saved': {
      id: '/account/saved'
      path: '/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AccountSavedRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cars/$stockId': {
      id: '/cars/$stockId'
      path: '/cars/$stockId'
      fullPath: '/cars/$stockId'
      preLoaderRoute: typeof CarsStockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/inquiries/': {
      id: '/account/inquiries/'
      path: '/inquiries'
      fullPath: '/account/inquiries/'
      preLoaderRoute: typeof AccountInquiriesIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/inquiries/$id': {
      id: '/account/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/account/inquiries/$id'
      preLoaderRoute: typeof AccountInquiriesIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vehicles/': {
      id: '/admin/vehicles/'
      path: '/vehicles'
      fullPath: '/admin/vehicles/'
      preLoaderRoute: typeof AdminVehiclesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vehicles/$id': {
      id: '/admin/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/admin/vehicles/$id'
      preLoaderRoute: typeof AdminVehiclesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/import-feed': {
      id: '/api/public/import-feed'
      path: '/api/public/import-feed'
      fullPath: '/api/public/import-feed'
      preLoaderRoute: typeof ApiPublicImportFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-inventory': {
      id: '/api/public/sync-inventory'
      path: '/api/public/sync-inventory'
      fullPath: '/api/public/sync-inventory'
      preLoaderRoute: typeof ApiPublicSyncInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSavedRoute: typeof AccountSavedRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountInquiriesIdRoute: typeof AccountInquiriesIdRoute
  AccountInquiriesIndexRoute: typeof AccountInquiriesIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountSavedRoute: AccountSavedRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountInquiriesIdRoute: AccountInquiriesIdRoute,
  AccountInquiriesIndexRoute: AccountInquiriesIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
  AdminVehiclesIdRoute: typeof AdminVehiclesIdRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminVehiclesIndexRoute: typeof AdminVehiclesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
  AdminVehiclesIdRoute: AdminVehiclesIdRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminVehiclesIndexRoute: AdminVehiclesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AllStockRoute: AllStockRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  HowToBuyRoute: HowToBuyRoute,
  InquiryRoute: InquiryRoute,
  LoginRoute: LoginRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OnSaleRoute: OnSaleRoute,
  OnePriceRoute: OnePriceRoute,
  CarsStockIdRoute: CarsStockIdRoute,
  ApiPublicImportFeedRoute: ApiPublicImportFeedRoute,
  ApiPublicSyncInventoryRoute: ApiPublicSyncInventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
