// Types for the tables added by 20260922100000_admin_inquiries_documents.sql.
//
// types.ts is regenerated by Lovable and must not be hand-edited, so the admin
// tables are declared here and merged onto the generated Database type instead.
// Once Lovable regenerates types.ts against the new schema, this file can be
// deleted and the imports pointed back at the generated Database.
import type { Database as Generated } from "./types";

export type AppRole = "admin" | "staff" | "customer";

export const INQUIRY_STATUSES = [
  "new",
  "contacted",
  "negotiating",
  "deal_won",
  "docs_ready",
  "shipped",
  "delivered",
  "deal_lost",
] as const;

export type InquiryStatus = (typeof INQUIRY_STATUSES)[number];

export const DOCUMENT_TYPES = [
  "invoice",
  "proforma_invoice",
  "bill_of_lading",
  "export_certificate",
  "inspection_report",
  "auction_sheet",
  "photos",
  "other",
] as const;

export type DocumentType = (typeof DOCUMENT_TYPES)[number];

/** Human labels for the status enum, used by both the admin and customer UIs. */
export const INQUIRY_STATUS_LABELS: Record<InquiryStatus, string> = {
  new: "New",
  contacted: "Contacted",
  negotiating: "Negotiating",
  deal_won: "Deal Won",
  docs_ready: "Documents Ready",
  shipped: "Shipped",
  delivered: "Delivered",
  deal_lost: "Deal Lost",
};

export const DOCUMENT_TYPE_LABELS: Record<DocumentType, string> = {
  invoice: "Invoice",
  proforma_invoice: "Proforma Invoice",
  bill_of_lading: "Bill of Lading",
  export_certificate: "Export Certificate",
  inspection_report: "Inspection Report",
  auction_sheet: "Auction Sheet",
  photos: "Photos",
  other: "Other",
};

export type UserRoleRow = {
  id: string;
  user_id: string;
  role: AppRole;
  created_at: string;
};

export type CustomerRow = {
  id: string;
  auth_user_id: string | null;
  name: string | null;
  email: string;
  phone: string | null;
  country: string | null;
  port: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type InquiryRow = {
  id: string;
  ref_no: string;
  customer_id: string | null;
  vehicle_id: string | null;
  name: string | null;
  email: string;
  phone: string | null;
  country: string | null;
  port: string | null;
  vehicle_text: string | null;
  message: string | null;
  status: InquiryStatus;
  agreed_price: number | null;
  currency: string | null;
  assigned_to: string | null;
  created_at: string;
  updated_at: string;
};

export type InquiryDocumentRow = {
  id: string;
  inquiry_id: string;
  doc_type: DocumentType;
  title: string;
  storage_path: string;
  file_size: number | null;
  mime_type: string | null;
  visible_to_customer: boolean;
  uploaded_by: string | null;
  uploaded_at: string;
};

export type InquiryNoteRow = {
  id: string;
  inquiry_id: string;
  note: string;
  author_id: string | null;
  created_at: string;
};

export type InquiryStatusHistoryRow = {
  id: string;
  inquiry_id: string;
  from_status: InquiryStatus | null;
  to_status: InquiryStatus;
  note: string | null;
  changed_by: string | null;
  changed_at: string;
};

/**
 * `Required_` names the columns an INSERT must supply. Everything else is
 * optional, because it is either nullable or filled in by a default or a
 * trigger — which is how the generated types model it too.
 */
type TableDef<Row, Required_ extends keyof Row> = {
  Row: Row;
  Insert: Pick<Row, Required_> & Partial<Omit<Row, Required_>>;
  Update: Partial<Row>;
  Relationships: [];
};

/**
 * The four browse lists — makes, body styles, categories and destination
 * countries — share one shape, so they share one row type.
 */
export type TaxonomyRow = {
  id: string;
  slug: string;
  name: string;
  image_url: string | null;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

/** Makes carry a logo rather than a tile image; otherwise identical. */
export type MakeRow = Omit<TaxonomyRow, "image_url"> & { logo_url: string | null };

export const DRIVE_SIDES = ["right", "left", "both"] as const;
export type DriveSide = (typeof DRIVE_SIDES)[number];

export const DRIVE_SIDE_LABELS: Record<DriveSide, string> = {
  right: "Right-hand drive",
  left: "Left-hand drive",
  both: "Either",
};

/**
 * A destination market. `drive_side` is what makes "Search By Country" a real
 * filter: nothing links a vehicle to a destination, but a market takes the
 * steering side it drives on, and that is recorded on every vehicle.
 * `vehicle_count` is an optional manual override for the figure on the tile.
 */
export type CountryRow = TaxonomyRow & {
  vehicle_count: number | null;
  drive_side: DriveSide;
};

export const TAXONOMIES = ["makes", "body_styles", "categories", "countries"] as const;
export type TaxonomyName = (typeof TAXONOMIES)[number];

export const TAXONOMY_LABELS: Record<TaxonomyName, string> = {
  makes: "Makes",
  body_styles: "Body Styles",
  categories: "Categories",
  countries: "Countries",
};

type GeneratedPublic = Generated["public"];
type GeneratedVehicles = GeneratedPublic["Tables"]["vehicles"];

/** The generated vehicle row plus the columns the dashboard added. */
export type VehicleRow = GeneratedVehicles["Row"] & {
  locked_fields: string[];
  is_manual: boolean;
  is_featured: boolean;
};

type VehicleExtras = { locked_fields: string[]; is_manual: boolean; is_featured: boolean };

/** Brand and contact details shown in the header, footer and Contact page. */
export type ContactSettings = {
  name: string;
  tagline: string;
  phone: string;
  email: string;
  address: string;
  /** Empty means fall back to the lettermark built from the company name. */
  logo_url: string;
  /** The badge in the header, e.g. "JPY, ¥". */
  currency_label: string;
};

/** A vehicle a customer has shortlisted. */
export type SavedVehicleRow = {
  id: string;
  customer_id: string;
  vehicle_id: string;
  created_at: string;
};

export type SiteSettingRow = {
  key: string;
  value: Record<string, string>;
  updated_at: string;
};

export type PageContentRow = {
  slug: string;
  title: string;
  hero_title: string;
  hero_subtitle: string | null;
  body: string | null;
  hero_image_url: string | null;
  cta_label: string | null;
  cta_href: string | null;
  meta_title: string | null;
  meta_description: string | null;
  updated_at: string;
};

/** One entry in the public top menu. */
export type NavItemRow = {
  id: string;
  label: string;
  href: string;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

/**
 * A repeatable item within a page: a buying step, an About statistic, or one of
 * the home page's promo panels. `variant` decides which slot in the home hero
 * grid a block fills; it is ignored on the other pages.
 */
export type PageBlockRow = {
  id: string;
  page_slug: string;
  title: string;
  body: string | null;
  image_url: string | null;
  cta_label: string | null;
  cta_href: string | null;
  variant: string;
  ends_at: string | null;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export const HOME_PANEL_VARIANTS = ["hero", "sale", "tile"] as const;
export type HomePanelVariant = (typeof HOME_PANEL_VARIANTS)[number];

export const HOME_PANEL_LABELS: Record<HomePanelVariant, string> = {
  hero: "Large promo (left)",
  sale: "Countdown panel",
  tile: "Small tile",
};

export const EDITABLE_PAGES = ["home", "how-to-buy", "about", "contact"] as const;
export type EditablePage = (typeof EDITABLE_PAGES)[number];

/** What the repeatable blocks are called on each page, for the admin UI. */
export const PAGE_BLOCK_LABELS: Record<EditablePage, { plural: string; singular: string } | null> =
  {
    home: { plural: "Selling points", singular: "selling point" },
    "how-to-buy": { plural: "Steps", singular: "step" },
    about: { plural: "Statistics", singular: "statistic" },
    contact: null,
  };

/** Pages whose hero carries an image and a call-to-action button. */
export const PAGES_WITH_HERO_IMAGE: EditablePage[] = ["home"];

export type AdminTables = {
  user_roles: TableDef<UserRoleRow, "user_id" | "role">;
  site_settings: TableDef<SiteSettingRow, "key">;
  page_content: TableDef<PageContentRow, "slug" | "title" | "hero_title">;
  page_blocks: TableDef<PageBlockRow, "page_slug" | "title">;
  nav_items: TableDef<NavItemRow, "label" | "href">;
  saved_vehicles: TableDef<SavedVehicleRow, "customer_id" | "vehicle_id">;
  customers: TableDef<CustomerRow, "email">;
  // ref_no and customer_id are assigned by the inquiries_before_insert trigger.
  inquiries: TableDef<InquiryRow, "email">;
  inquiry_documents: TableDef<InquiryDocumentRow, "inquiry_id" | "title" | "storage_path">;
  inquiry_notes: TableDef<InquiryNoteRow, "inquiry_id" | "note">;
  inquiry_status_history: TableDef<InquiryStatusHistoryRow, "inquiry_id" | "to_status">;
  makes: TableDef<MakeRow, "slug" | "name">;
  body_styles: TableDef<TaxonomyRow, "slug" | "name">;
  categories: TableDef<TaxonomyRow, "slug" | "name">;
  countries: TableDef<CountryRow, "slug" | "name">;
  vehicles: {
    Row: VehicleRow;
    Insert: GeneratedVehicles["Insert"] & Partial<VehicleExtras>;
    Update: GeneratedVehicles["Update"] & Partial<VehicleExtras>;
    Relationships: GeneratedVehicles["Relationships"];
  };
};

/**
 * The generated Database plus the admin tables. `vehicles` is replaced rather
 * than intersected, so the added columns do not collide with the generated
 * definition of the same table.
 */
export type AppDatabase = Omit<Generated, "public"> & {
  public: Omit<GeneratedPublic, "Tables"> & {
    Tables: Omit<GeneratedPublic["Tables"], "vehicles"> & AdminTables;
  };
};

export const DOCUMENT_BUCKET = "inquiry-docs";
